### ISSUE TITLE
Fails with com.android.tools.build:gradle:1.1.0

### ISSUE THREAD

**Issue by relefant** [uPhyca/gradle-android-aspectj-plugin#14]
I get the following error on build:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> No such property: bootClasspath for class: com.android.build.gradle.AppPlugin

Works with
com.android.tools.build:gradle:1.0.0

**Comment by bnjmnd** [comment]
Same issue here : 
```Error:No such property: bootClasspath for class: com.android.build.gradle.AppPlugin```

With com.android.tools.build:gradle:1.1.0

**Comment by leo-k** [comment]
Same issue, works with com.android.tools.build:gradle:1.0.0, but 1.1.0+ fail with same error as mentioned above.

**Comment by polenchheang** [comment]
This would give some clues http://stackoverflow.com/a/28582045/679102

**Comment by leo-k** [comment]
Right, might be related, except in this case is not working with 1.1.0, 1.1.1, 1.1.2. Where as in that SO question/answer the problem was with 1.1.0-rcX

**Comment by esmasui** [comment]
fixed via 329031afa98f4568e8f857999bc97bcb8e2211ef
