### ISSUE TITLE
Exception while buidling android library project

### ISSUE THREAD

**Issue by sneureiter** [uPhyca/gradle-android-aspectj-plugin#16]
I got the following error while building an android-library-project:

20:37:53.716 [ERROR] [org.gradle.BuildExceptionReporter] 
20:37:53.716 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
20:37:53.717 [ERROR] [org.gradle.BuildExceptionReporter] 
20:37:53.717 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
20:37:53.717 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':piwik_sdk:compileDebugAspectj'.
20:37:53.718 [ERROR] [org.gradle.BuildExceptionReporter] > result cannot be resolved to a variable
20:37:53.718 [ERROR] [org.gradle.BuildExceptionReporter] 
20:37:53.718 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
20:37:53.719 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':piwik_sdk:compileDebugAspectj'.

The exceptions occurs in the following line.

20:37:53.735 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.GradleException: result cannot be resolved to a variable
20:37:53.735 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.uphyca.gradle.android.AspectjCompile.compile(AspectjCompile.groovy:70)
20:37:53.736 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)

I am using plugin version 0.9.9
Thanks!

**Comment by umesh-k** [comment]
I am also facing the same issue.. @sneureiter are you able to resolve this issue yet ?
