### ISSUE TITLE
Unsupported major.minor version 52.0 using AspectJ 0.9.10

### ISSUE THREAD

**Issue by carlonzo** [uPhyca/gradle-android-aspectj-plugin#18]
After the last update I am receiving the error :
Error:(14, 0) Cause: com/uphyca/gradle/android/AndroidAspectJPlugin : Unsupported major.minor version 52.0

http://stackoverflow.com/questions/10382929/unsupported-major-minor-version-51-0

have you compiled using Java 8?

**Comment by esmasui** [comment]
fixed via ef856acc910cc12986f0c4e9b94f6fc891cce6e8 and released as 0.9.11, thanks.

**Comment by carlonzo** [comment]
thanks!
