### ISSUE TITLE
how to work with androidannotations？

### ISSUE THREAD

**Issue by wangzhiqiang** [uPhyca/gradle-android-aspectj-plugin#23]
use android studio and build with gardlw .
but

Error:Execution failed for task ':app:compileDebugAspectj'.
> The import  "x.x.xTabPageItemFragment_" cannot be resolved

"TabPageItemFragment_"  is androidannotations compile source

**Comment by Archinamon** [comment]
My mind it should be resolved via execution order:
:app:compileDebugAspectj should be executed AFTER :app:compileDebugJava_ (AA compile task).
Maybe there exists some workaround for this situation?

**Comment by wangzhiqiang** [comment]
Thanks ! 
I have change to use AspectJ-gradle.

**Comment by Archinamon** [comment]
You can try my own plugin, based on this uPhica's one. AspectJ-gradle doesn't support native aspect language, that makes me to refuse using it.
https://github.com/Archinamon/GradleAspectJ-Android
