### ISSUE TITLE
Multi-flavour project fails: "Unknown location : SOURCE_OUTPUT"

### ISSUE THREAD

**Issue by BrantApps** [uPhyca/gradle-android-aspectj-plugin#27]
## To replicate
* Install the latest production _Android Studio_ tooling (v1.2.2 at the time of writing)
** NB: Build tooling being used is ````'com.android.tools.build:gradle:1.2.3'````
* Create a multi-flavoured project (not sure if this is relevant but it is my set up - see _Snippet 1_.
```java
    |_ debug
    |_ main
    |_ release
    |_ withGoogleMaps
    |_ withOsm
```
_Snippet 1_: Project structure exhibiting the failure
* Follow the [usage instructions][1] to set up the weaving
* Attempt to install the latest version of your app leveraging AOP

## Expected result
* Code is weaved (````@Transactional```` annotation in my case - copying Spring's db transaction aspecting)

## Actual result
* Unfortunately building fails with the exception;
```java
:app:compileWithGoogleMapsDebugAspectj
Internal compiler error: java.lang.IllegalArgumentException: Unknown location : SOURCE_OUTPUT at org.aspectj.org.eclipse.jdt.internal.compiler.apt.util.EclipseFileManager.getFileForOutput(EclipseFileManager.java:420)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileWithGoogleMapsDebugAspectj'.
> Internal compiler error: java.lang.IllegalArgumentException: Unknown location : SOURCE_OUTPUT at org.aspectj.org.eclipse.jdt.internal.compiler.apt.util.EclipseFileManager.getFileForOutput(EclipseFileManager.java:420)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.584 secs
```

[1]: https://github.com/uPhyca/gradle-android-aspectj-plugin

**Comment by BrantApps** [comment]
This is directly related to the user of ````dagger-compiler```` - closing.

**Comment by renaudcerrato** [comment]
@BrantApps : how did you circumvented this?

**Comment by BrantApps** [comment]
Hi @renaudcerrato - I've documented the workaround on Stackoverflow [here](http://stackoverflow.com/questions/28546803/is-it-possible-to-integrate-dagger-and-aspectj-in-an-android-studio-project/32827331#32827331) - let me know if it works for you. I'm afraid that the real solution here though is to remove aspectj from my Android project. The Jack & Jill complier may well completely break this sort of thing since it will go from .java to .dex directly...not via .class....the step needed for AspectJ as I know it. I think the proguard guy said that there will be ways around it but I don't know how to build such support. My next steps will be to remove AspectJ from my app I think...

**Comment by renaudcerrato** [comment]
@BrantApps thanks for the feedback - I'm using a fork of that plugin, and I created an issue https://github.com/Archinamon/GradleAspectJ-Android/issues/5, the guy is very responsive - hope we we'll find a solution.
