### ISSUE TITLE
with java1.8 lambda in android studio

### ISSUE THREAD

**Issue by momodae** [uPhyca/gradle-android-aspectj-plugin#42]
hello
      I am a chinese, and I use Android studio with java1.8 lambda,i found some question. please help me,sorry,my english is very bad...

**Comment by esmasui** [comment]
Hi,
Did you mean that you are using retrolambda?

**Comment by momodae** [comment]
yes,yes.android studio use only retrolambda

**Comment by esmasui** [comment]
We don't currently support retrolambda.
retrolambda support will be enhanced in the future version, or you can try another libraries such as https://github.com/Archinamon/GradleAspectJ-Android .

Thank you.

**Comment by momodae** [comment]
Thank you,Greeting you warmly with sincere wishes for healthy, happy, and wonderful days.
