### ISSUE TITLE
Support for Project Lombok / hrisey?

### ISSUE THREAD

**Issue by kst83** [uPhyca/gradle-android-aspectj-plugin#7]
I'd like to use Monkeytalk (which depends on aspectj) together with Project Lombok / hrisey.
However, I get the following error on compile_
```
You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
```
According to https://weblogs.java.net/blog/fabriziogiudici/archive/2011/07/19/making-lombok-aspectj-and-maven-co-exist, this could probably be avoided by calling iajc with the -inpath option.
Would it be possible to implement an option to do this into this project?

**Comment by esmasui** [comment]
This project is now deprecated. 
Please use https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx instead.
Thank you.
